[general]
start = "bun run dev"
cookbookPort = 8000

[projects.__test__]
port = 9000
type = "milkio"
typiaMode = "bundler"
start = ["bun", "run", "index.ts"]
build = ["bun", "run", ".milkio/bun-build.ts"]
